on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

name: CI

permissions:
  contents: read

jobs:
  code-style:
    name: Code style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer,phive

      - name: Run PHP-CS-Fixer
        run: |
          composer install --no-interaction --no-ansi --no-progress
          composer run format

  validate:
      name: Validate
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer,phive

      - name: Analyze with PHPStan
        run: |
          composer install --no-interaction --no-ansi --no-progress
          composer run analyze

